// startproject/_temp_files/vue3/components/FormInputs/Switch.vue
<script setup>
defineProps({
  field: Object,
  form: Object,
});
</script>

<template>
  <label class="relative inline-flex items-center cursor-pointer">
    <input v-bind="field.attrs" class="sr-only peer" v-model="form[field.name]" />
    <div
      class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"
    ></div>
  </label>
</template>

// startproject/_temp_files/components/FormInputs/Switch.jsx
export default function Switch(props) {
  if (props.plain) return <input {...props} />;

  return (
    <label className="relative inline-flex items-center cursor-pointer">
      <input
        {...props}
        className="sr-only peer"
        onChange={(e) => {
          props.onChange({ target: { value: e.target.checked } });
        }}
        checked={props.value}
      />
      <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"></div>
    </label>
  );
}
