// startproject/_temp_files/react/components/Form.jsx
import { router, useForm } from '@inertiajs/react';
import Button from '../components/Button';
import FormField from '../components/FormField';

export default function Form({
  form,
  className,
  buttonClasses,
  buttonWrapperClasses,
  buttonExtras,
  fieldModifiers,
  fieldsWrapperClasses,
  fieldWrapperClasses,
  preserveState,
  preserveScroll,
  submitEndpoint,
  preFieldschildren,
  postFieldsChildren,
}) {
  const { data, transform, setData, post, processing, errors } = useForm(form.initial);
  const submit = (e) => {
    e.preventDefault();
    post(submitEndpoint || '', {
      forceFormData: true,
      preserveState: preserveState === false ? false : true,
      preserveScroll: preserveScroll === false ? false : true,
    });
  };

  const makeFormData = (data) => {
    const formData = new FormData();
    for (const key of Object.keys(data)) {
      const value = data[key];
      if (Array.isArray(value)) for (const val of value) formData.append(key, val);
      else formData.append(key, data[key]);
    }

    return formData;
  };
  transform(makeFormData);

  const manualSubmit = (newData, options) => {
    const manualData = { ...data, ...newData };
    router.post(submitEndpoint || '', makeFormData(manualData), {
      forceFormData: true,
      preserveState: preserveState === false ? false : true,
      preserveScroll: preserveScroll === false ? false : true,
      ...options,
    });
  };
  return (
    <form onSubmit={submit} className={className}>
      {preFieldschildren}
      <div className={fieldsWrapperClasses}>
        {form.fields.map((field) => (
          <FormField
            key={field.name}
            {...field}
            onChange={(e) => setData(field.name, e.target.value)}
            manualSubmit={manualSubmit}
            value={data?.[field.name]}
            errors={errors?.[field.name]}
            {...(fieldModifiers?.[field.name] || {
              wrapperClass: fieldWrapperClasses,
            })}
          />
        ))}
      </div>
      {postFieldsChildren}
      <div className={buttonWrapperClasses}>
        <Button type="submit mt-2" loading={processing} className={buttonClasses}>
          {form.submit_button_text}
        </Button>
        {buttonExtras}
      </div>
      {errors.__all__ && (
        <p className="text-xs text-red-600 mt-2" id="all-error">
          {errors.__all__.map((error) => error.message)}
        </p>
      )}
    </form>
  );
}

// startproject/_temp_files/vue3/components/Form.vue
<script setup>
import { useForm } from '@inertiajs/vue3';
import Button from './Button.vue';
import FormField from './FormField.vue';

const props = defineProps({ form: Object });
const newForm = useForm(props.form.initial);
const submit = () => {
  newForm
    .transform((data) => {
      const formData = new FormData();
      for (const key of Object.keys(data)) {
        const value = data[key];
        if (Array.isArray(value)) for (const val of value) formData.append(key, val);
        else formData.append(key, data[key]);
      }
      return formData;
    })
    .post('', { forceFormData: true, preserveScroll: true });
};
</script>

<template>
  <form @submit.prevent="submit">
    <div class="grid gap-y-4">
      <div v-for="field in form.fields">
        <FormField :field="field" :errors="newForm.errors?.[field.name]" :form="newForm" />
      </div>
      <Button
        type="submit"
        :loading="newForm.processing"
        class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800"
      >
        {{ form.submit_button_text }}
      </Button>
    </div>
    <div v-if="newForm.errors.__all__">
      <p class="text-xs text-red-600 mt-2" v-for="error in newForm.errors.__all__">
        {{ error.message }}
      </p>
    </div>
  </form>
</template>
